-- EJECUTESE VARIAS VECES PARA ASEGURAR FUNCIONAMIENTO ESPERADO
DELETE FROM AUTORIZACION;
DELETE FROM CLIENTE;
DELETE FROM CUENTA;
DELETE FROM CUENTA_FINTECH;
DELETE FROM CUENTA_REFERENCIA;
DELETE FROM DEPOSITAR_EN;
DELETE FROM DIVISA;
DELETE FROM EMPRESA;
DELETE FROM INDIVIDUAL;
DELETE FROM MOVIMIENTOS;
DELETE FROM PERSONA_AUTORIZADA;
DELETE FROM POOLED_ACCOUNT;
DELETE FROM SEGREGADA;
DELETE FROM TARJETAS;
DELETE FROM TRANSACCION;