-- SE INSERTAN DATOS PARA PRUEBAS
    INSERT INTO CUENTA VALUES(-1, 'SEGREGADA_DEFAULT', NULL);
    
    INSERT INTO CLIENTE VALUES(-1, 'INDIVIDUAL_DEFAULT', 'INDIVIDUAL', 'ACTIVO', SYSDATE, NULL, 'DEFAULT_ADDRESS', 'DEFAULT_CITY', 'DEFAULT_CP', 'DEFAULT_COUNTRY');
    INSERT INTO INDIVIDUAL VALUES(-1, 'DEFAULT_NAME', 'DEFAULT_SURNAME', NULL);
    
    INSERT INTO CUENTA_FINTECH VALUES(-1, -1, 'ACTIVO', SYSDATE, NULL, NULL);
    INSERT INTO CUENTA VALUES(-2, 'REFERENCIA_DEFAULT', NULL);
    INSERT INTO DIVISA VALUES('EUR', 'EURO', NULL, 1);
    INSERT INTO CUENTA_REFERENCIA VALUES(-2, 'DEFAULT_BANK', NULL, NULL, 42069, NULL, 'ACTIVO', 'EUR');
    INSERT INTO SEGREGADA VALUES(-1, 0, -2);
    
    INSERT INTO CLIENTE VALUES(-2, 'EMPRESA_DEFAULT', 'EMPRESA', 'ACTIVO', SYSDATE, NULL, 'DEFAULT_ADDRESS', 'DEFAULT_CITY', 'DEFAULT_CP', 'DEFAULT_COUNTRY');
    INSERT INTO EMPRESA VALUES(-2, 'SA');
    
    INSERT INTO CUENTA VALUES(-3, 'POOLED_DEFAULT', NULL);
    INSERT INTO CUENTA_FINTECH VALUES(-3, -2, 'ACTIVO', SYSDATE, NULL, NULL);
    INSERT INTO POOLED_ACCOUNT VALUES(-3);
    INSERT INTO DEPOSITAR_EN VALUES(420, -2, -3);
    
    INSERT INTO PERSONA_AUTORIZADA VALUES(-1, 'DEFAULT_PA', 'DEFAULT_NAME', 'DEFAULT_SURNAME', 'DEFAULT_ADDRESS', NULL, SYSDATE, 'ACTIVO', NULL);
    INSERT INTO AUTORIZACION VALUES('O', -1, -2); -- O FOR OPERATIVO
    
    INSERT INTO TRANSACCION VALUES(1, SYSDATE, 69, SYSDATE, 'TRANSFERENCIA', NULL, NULL, 'EUR', 'EUR', -1, -3);