CREATE OR REPLACE VIEW V_PAGOS_PENDIENTES(IDENTIFICACION, NUMERO_TARJETA, PENDIENTES, ABREVIATURA)
    AS (SELECT C.IDENTIFICACION, T.NUMERO, M.ESTADO, D.ABREVIATURA
    FROM CLIENTE C, TARJETAS T, MOVIMIENTOS M, DIVISA D
    WHERE
        C.ID = T.CLIENTE_ID AND
        T.NUMERO = M.NUMERO_TARJETA AND
        M.DIVISA = D.ABREVIATURA AND
        M.ESTADO = 'PENDIENTES');