CREATE OR REPLACE VIEW V_TARJETA_MENSUAL (IDENTIFICACION, NUMERO_TARJETA, GASTO, ABREVIATURA) 
    AS (SELECT C.IDENTIFICACION, T.NUMERO, SUM(M.CANTIDAD), D.ABREVIATURA  
    FROM CLIENTE C, TARJETAS T, MOVIMIENTOS M, DIVISA D
    WHERE
        C.ID = T.CLIENTE_ID AND
        T.NUMERO = M.NUMERO_TARJETA AND
        M.DIVISA = D.ABREVIATURA
    GROUP BY D.ABREVIATURA,C.IDENTIFICACION, T.NUMERO);